using System.Data.Common;
using Microsoft.Data.Sqlite;

namespace SovietTransistors.Data;

/// <summary>Реализация для SQLite: файл базы создаётся при первом обращении, хранение — UTF-8.</summary>
public sealed class SqliteDatabase : RelationalTransistorDatabase
{
    private readonly string _connectionString;

    public SqliteDatabase(string databasePath)
    {
        _connectionString = new SqliteConnectionStringBuilder
        {
            DataSource = databasePath,
            Mode = SqliteOpenMode.ReadWriteCreate,
        }.ToString();
    }

    protected override DbConnection OpenConnection()
    {
        var connection = new SqliteConnection(_connectionString);
        connection.Open();
        // SQLite требует включения внешних ключей для каждого соединения (каскадное удаление данных).
        using DbCommand pragma = connection.CreateCommand();
        pragma.CommandText = "PRAGMA foreign_keys = ON";
        pragma.ExecuteNonQuery();
        return connection;
    }

    // Для перехода на PostgreSQL/MariaDB: унаследуйте RelationalTransistorDatabase
    // и переопределите OpenConnection() (Npgsql/MySqlConnector) и CreateTableSql
    // (id: GENERATED BY DEFAULT AS IDENTITY / AUTO_INCREMENT). DML менять не нужно.
    protected override string CreateTableSql => """
        CREATE TABLE IF NOT EXISTS transistors (
            Id            INTEGER PRIMARY KEY AUTOINCREMENT,
            Material      TEXT    NOT NULL,     -- 1. материал: Г|1, К|2, А|3, И|4
            Subclass      TEXT    NOT NULL,     -- 2. подкласс: Т или П
            Assembly      TEXT        NULL,     -- 2.1. сборка: С (необязательно)
            Feature       INTEGER NOT NULL,     -- 3. эксплуатационный признак: 1–9
            DevNumber     INTEGER NOT NULL,     -- 4. номер разработки: 01–999
            Letters       TEXT    NOT NULL,     -- 5. классификация: 1–2 заглавные русские буквы
            Modification  INTEGER     NULL,     -- 6. модификация: 1–9 (необязательно)
            ChipVariant   INTEGER     NULL,     -- 7. бескорпусное исполнение: 1–6 (необязательно)
            CONSTRAINT chk_material     CHECK (Material IN ('Г','1','К','2','А','3','И','4')),
            CONSTRAINT chk_subclass     CHECK (Subclass IN ('Т','П')),
            CONSTRAINT chk_assembly     CHECK (Assembly IS NULL OR Assembly = 'С'),
            CONSTRAINT chk_feature      CHECK (Feature BETWEEN 1 AND 9),
            CONSTRAINT chk_dev_number   CHECK (DevNumber BETWEEN 1 AND 999),
            CONSTRAINT chk_letters      CHECK (Letters <> ''),
            CONSTRAINT chk_modification CHECK (Modification IS NULL OR (Modification BETWEEN 1 AND 9)),
            CONSTRAINT chk_chip_variant CHECK (ChipVariant IS NULL OR (ChipVariant BETWEEN 1 AND 6)),
            CONSTRAINT uq_transistor    UNIQUE (Material, Subclass, Assembly, Feature, DevNumber, Letters, Modification, ChipVariant)
        );

        CREATE TABLE IF NOT EXISTS transistor_attributes (
            TransistorId INTEGER PRIMARY KEY REFERENCES transistors(Id) ON DELETE CASCADE,
            Structure        TEXT    NULL,   -- структура проводимости: npn, pnp, n-fet, p-fet…
            Technology       TEXT    NULL,   -- технология: сплавная, планарная, эпитаксиальная…
            Package          TEXT    NULL,   -- корпус: КТ-13, TO-92…
            PackageMaterial  TEXT    NULL,   -- материал корпуса: металл, металлокерамика, пластик
            ColorMarking     TEXT    NULL,   -- цветовая маркировка (если обозначения на корпусе нет)
            Pinout           TEXT    NULL,   -- цоколёвка: КБЭ, 1-Э 2-К 3-Б…
            EsdSensitive     INTEGER NULL,   -- повышенная чувствительность к статическому напряжению: 0/1
            MilitaryGrade    INTEGER NULL,   -- военное исполнение: 0/1
            RadiationHardened INTEGER NULL, -- радиационная стойкость: 0/1
            Tu               TEXT    NULL,   -- обозначение ТУ/ОТУ
            Notes            TEXT    NULL,   -- примечание
            YearFrom         INTEGER NULL,   -- год начала выпуска (1949–2100)
            YearTo           INTEGER NULL,   -- год окончания выпуска (NULL — выпускался на момент описания)
            MassMax          REAL    NULL,   -- масса «не более», г
            DatasheetUrl     TEXT    NULL,   -- ссылка на документацию
            CONSTRAINT chk_esd       CHECK (EsdSensitive IS NULL OR EsdSensitive IN (0, 1)),
            CONSTRAINT chk_military  CHECK (MilitaryGrade IS NULL OR MilitaryGrade IN (0, 1)),
            CONSTRAINT chk_radiation CHECK (RadiationHardened IS NULL OR RadiationHardened IN (0, 1)),
            CONSTRAINT chk_years CHECK (
                (YearFrom IS NULL OR (YearFrom >= 1949 AND YearFrom <= 2100))
                AND (YearTo IS NULL OR (YearTo >= 1949 AND YearTo <= 2100))
                AND (YearFrom IS NULL OR YearTo IS NULL OR YearFrom < YearTo)
            ),
            CONSTRAINT chk_mass CHECK (MassMax IS NULL OR MassMax > 0),
            CONSTRAINT chk_any_attribute CHECK (
                Structure IS NOT NULL OR Technology IS NOT NULL OR Package IS NOT NULL
                OR PackageMaterial IS NOT NULL OR ColorMarking IS NOT NULL OR Pinout IS NOT NULL
                OR EsdSensitive IS NOT NULL OR MilitaryGrade IS NOT NULL OR RadiationHardened IS NOT NULL
                OR Tu IS NOT NULL OR Notes IS NOT NULL OR YearFrom IS NOT NULL OR YearTo IS NOT NULL
                OR MassMax IS NOT NULL OR DatasheetUrl IS NOT NULL
            )
        );

        CREATE TABLE IF NOT EXISTS manufacturers (
            Id   INTEGER PRIMARY KEY AUTOINCREMENT,
            Name TEXT NOT NULL UNIQUE
        );

        CREATE TABLE IF NOT EXISTS transistor_manufacturers (
            TransistorId   INTEGER NOT NULL REFERENCES transistors(Id) ON DELETE CASCADE,
            ManufacturerId INTEGER NOT NULL REFERENCES manufacturers(Id) ON DELETE CASCADE,
            PRIMARY KEY (TransistorId, ManufacturerId)
        );

        CREATE TABLE IF NOT EXISTS electrical_parameters (
            Id            INTEGER PRIMARY KEY AUTOINCREMENT,
            TransistorId INTEGER NOT NULL REFERENCES transistors(Id) ON DELETE CASCADE,
            Parameter     TEXT    NOT NULL,   -- h21e | h21b | FGran | UGran | UkeNas | UbeNas | Ikbo | Iebo | Ikeo | Ikep | h11 | Ck | Ce | Tauk | Ton | Toff | KShum | PVyh | KUr | Kpd
            ValueMin      REAL        NULL,   -- «не менее» / нижняя граница (h21* безразмерный; FGran МГц; U* В; I* мкА; h11 Ом; C* пФ; Tauk пс; T* нс; KShum/KUr дБ; PVyh Вт; Kpd %)
            ValueMax      REAL        NULL,   -- «не более» / верхняя граница
            Uke           REAL        NULL,   -- условие: напряжение коллектор-эмиттер, В
            Ukb           REAL        NULL,   -- условие: напряжение коллектор-база, В
            Ueb           REAL        NULL,   -- условие: напряжение эмиттер-база, В
            Ik            REAL        NULL,   -- условие: ток коллектора, мА
            Ie            REAL        NULL,   -- условие: ток эмиттера, мА
            Ib            REAL        NULL,   -- условие: ток базы, мА (только Ton/Toff)
            Freq          REAL        NULL,   -- условие: частота, МГц (только KShum/PVyh/KUr/Kpd)
            Rg            REAL        NULL,   -- условие: сопротивление генератора, Ом (только KShum)
            Rbe           REAL        NULL,   -- условие: сопротивление в цепи база-эмиттер, Ом (только Ikep)
            Temp          REAL        NULL,   -- условие: температура среды, °C
            CONSTRAINT chk_param_code CHECK (Parameter IN ('h21e','h21b','FGran','UGran','UkeNas','UbeNas','Ikbo','Iebo','Ikeo','Ikep','h11','Ck','Ce','Tauk','Ton','Toff','KShum','PVyh','KUr','Kpd')),
            CONSTRAINT chk_param_value CHECK (
                CASE Parameter
                    WHEN 'h21e'     THEN CASE WHEN ValueMin IS NOT NULL AND (ValueMax IS NULL OR ValueMin <= ValueMax) THEN 1 ELSE 0 END
                    WHEN 'h21b'     THEN CASE WHEN ValueMin IS NOT NULL AND (ValueMax IS NULL OR ValueMin <= ValueMax) THEN 1 ELSE 0 END
                    WHEN 'FGran'    THEN CASE WHEN ValueMin IS NOT NULL AND ValueMax IS NULL THEN 1 ELSE 0 END
                    WHEN 'UGran'    THEN CASE WHEN ValueMin IS NOT NULL AND ValueMax IS NULL THEN 1 ELSE 0 END
                    WHEN 'UkeNas'   THEN CASE WHEN ValueMax IS NOT NULL AND ValueMin IS NULL THEN 1 ELSE 0 END
                    WHEN 'UbeNas'   THEN CASE WHEN ValueMax IS NOT NULL AND ValueMin IS NULL THEN 1 ELSE 0 END
                    WHEN 'Ikbo'     THEN CASE WHEN ValueMax IS NOT NULL AND ValueMin IS NULL THEN 1 ELSE 0 END
                    WHEN 'Iebo'     THEN CASE WHEN ValueMax IS NOT NULL AND ValueMin IS NULL THEN 1 ELSE 0 END
                    WHEN 'Ikeo'     THEN CASE WHEN ValueMax IS NOT NULL AND ValueMin IS NULL THEN 1 ELSE 0 END
                    WHEN 'Ikep'     THEN CASE WHEN ValueMax IS NOT NULL AND ValueMin IS NULL THEN 1 ELSE 0 END
                    WHEN 'h11'      THEN CASE WHEN ValueMin IS NOT NULL AND ValueMax IS NULL THEN 1 ELSE 0 END
                    WHEN 'Ck'       THEN CASE WHEN ValueMax IS NOT NULL AND ValueMin IS NULL THEN 1 ELSE 0 END
                    WHEN 'Ce'       THEN CASE WHEN ValueMax IS NOT NULL AND ValueMin IS NULL THEN 1 ELSE 0 END
                    WHEN 'Tauk'     THEN CASE WHEN ValueMax IS NOT NULL AND ValueMin IS NULL THEN 1 ELSE 0 END
                    WHEN 'Ton'      THEN CASE WHEN ValueMax IS NOT NULL AND ValueMin IS NULL THEN 1 ELSE 0 END
                    WHEN 'Toff'     THEN CASE WHEN ValueMax IS NOT NULL AND ValueMin IS NULL THEN 1 ELSE 0 END
                    WHEN 'KShum'    THEN CASE WHEN ValueMax IS NOT NULL AND ValueMin IS NULL THEN 1 ELSE 0 END
                    WHEN 'PVyh'     THEN CASE WHEN ValueMin IS NOT NULL AND ValueMax IS NULL THEN 1 ELSE 0 END
                    WHEN 'KUr'      THEN CASE WHEN ValueMin IS NOT NULL AND ValueMax IS NULL THEN 1 ELSE 0 END
                    WHEN 'Kpd'      THEN CASE WHEN ValueMin IS NOT NULL AND ValueMax IS NULL AND ValueMin <= 100 THEN 1 ELSE 0 END
                    ELSE 0
                END = 1
            ),
            CONSTRAINT chk_param_conditions CHECK (
                CASE Parameter
                    WHEN 'h21e' THEN CASE WHEN
                        (Uke IS NOT NULL AND Ik IS NOT NULL AND Ukb IS NULL AND Ueb IS NULL AND Ie IS NULL)
                     OR (Ukb IS NOT NULL AND Ie IS NOT NULL AND Uke IS NULL AND Ueb IS NULL AND Ik IS NULL)
                    THEN 1 ELSE 0 END
                    WHEN 'FGran' THEN CASE WHEN
                        (Uke IS NOT NULL AND Ik IS NOT NULL AND Ukb IS NULL AND Ueb IS NULL AND Ie IS NULL)
                     OR (Ukb IS NOT NULL AND Ie IS NOT NULL AND Uke IS NULL AND Ueb IS NULL AND Ik IS NULL)
                    THEN 1 ELSE 0 END
                    WHEN 'UGran' THEN CASE WHEN
                        (Ik IS NOT NULL AND Ie IS NULL AND Uke IS NULL AND Ukb IS NULL AND Ueb IS NULL)
                     OR (Ie IS NOT NULL AND Ik IS NULL AND Uke IS NULL AND Ukb IS NULL AND Ueb IS NULL)
                    THEN 1 ELSE 0 END
                    WHEN 'UkeNas' THEN CASE WHEN
                        (Ik IS NOT NULL AND Ie IS NULL AND Uke IS NULL AND Ukb IS NULL AND Ueb IS NULL)
                     OR (Ie IS NOT NULL AND Ik IS NULL AND Uke IS NULL AND Ukb IS NULL AND Ueb IS NULL)
                    THEN 1 ELSE 0 END
                    WHEN 'UbeNas' THEN CASE WHEN
                        (Ik IS NOT NULL AND Ie IS NULL AND Uke IS NULL AND Ukb IS NULL AND Ueb IS NULL)
                     OR (Ie IS NOT NULL AND Ik IS NULL AND Uke IS NULL AND Ukb IS NULL AND Ueb IS NULL)
                    THEN 1 ELSE 0 END
                    WHEN 'Ikbo' THEN CASE WHEN Ukb IS NOT NULL AND Uke IS NULL AND Ueb IS NULL AND Ik IS NULL AND Ie IS NULL THEN 1 ELSE 0 END
                    WHEN 'Iebo' THEN CASE WHEN Ueb IS NOT NULL AND Uke IS NULL AND Ukb IS NULL AND Ik IS NULL AND Ie IS NULL THEN 1 ELSE 0 END
                    WHEN 'Ikeo' THEN CASE WHEN Uke IS NOT NULL AND Ukb IS NULL AND Ueb IS NULL AND Ik IS NULL AND Ie IS NULL THEN 1 ELSE 0 END
                    WHEN 'Ikep' THEN CASE WHEN Uke IS NOT NULL AND Ukb IS NULL AND Ueb IS NULL AND Ik IS NULL AND Ie IS NULL THEN 1 ELSE 0 END
                    WHEN 'h11'  THEN CASE WHEN Uke IS NOT NULL AND Ik IS NOT NULL AND Ukb IS NULL AND Ueb IS NULL AND Ie IS NULL THEN 1 ELSE 0 END
                    WHEN 'Ck'   THEN CASE WHEN Ukb IS NOT NULL AND Uke IS NULL AND Ueb IS NULL AND Ik IS NULL AND Ie IS NULL THEN 1 ELSE 0 END
                    WHEN 'Ce'   THEN CASE WHEN Ueb IS NOT NULL AND Uke IS NULL AND Ukb IS NULL AND Ik IS NULL AND Ie IS NULL THEN 1 ELSE 0 END
                    WHEN 'Tauk' THEN CASE WHEN Ukb IS NOT NULL AND Ie IS NOT NULL AND Uke IS NULL AND Ueb IS NULL AND Ik IS NULL THEN 1 ELSE 0 END
                    WHEN 'h21b' THEN CASE WHEN Ukb IS NOT NULL AND Ie IS NOT NULL AND Uke IS NULL AND Ueb IS NULL AND Ik IS NULL THEN 1 ELSE 0 END
                    WHEN 'Ton'  THEN CASE WHEN Ik IS NOT NULL AND Ib IS NOT NULL AND Uke IS NULL AND Ukb IS NULL AND Ueb IS NULL AND Ie IS NULL THEN 1 ELSE 0 END
                    WHEN 'Toff' THEN CASE WHEN Ik IS NOT NULL AND Ib IS NOT NULL AND Uke IS NULL AND Ukb IS NULL AND Ueb IS NULL AND Ie IS NULL THEN 1 ELSE 0 END
                    WHEN 'KShum' THEN CASE WHEN
                        (Uke IS NOT NULL AND Ik IS NOT NULL AND Ukb IS NULL AND Ueb IS NULL AND Ie IS NULL)
                     OR (Ukb IS NOT NULL AND Ie IS NOT NULL AND Uke IS NULL AND Ueb IS NULL AND Ik IS NULL)
                    THEN 1 ELSE 0 END
                    WHEN 'PVyh' THEN CASE WHEN
                        ((Uke IS NOT NULL AND Ik IS NOT NULL) OR (Uke IS NULL AND Ik IS NULL))
                        AND Ukb IS NULL AND Ueb IS NULL AND Ie IS NULL
                    THEN 1 ELSE 0 END
                    WHEN 'KUr' THEN CASE WHEN
                        ((Uke IS NOT NULL AND Ik IS NOT NULL) OR (Uke IS NULL AND Ik IS NULL))
                        AND Ukb IS NULL AND Ueb IS NULL AND Ie IS NULL
                    THEN 1 ELSE 0 END
                    WHEN 'Kpd' THEN CASE WHEN
                        ((Uke IS NOT NULL AND Ik IS NOT NULL) OR (Uke IS NULL AND Ik IS NULL))
                        AND Ukb IS NULL AND Ueb IS NULL AND Ie IS NULL
                    THEN 1 ELSE 0 END
                    ELSE 0
                END = 1
            ),
            CONSTRAINT chk_param_frequency CHECK (
                CASE WHEN Parameter IN ('KShum','PVyh','KUr','Kpd') THEN Freq IS NOT NULL ELSE Freq IS NULL END = 1
            ),
            CONSTRAINT chk_param_extra_conds CHECK (
                (Parameter = 'KShum' OR Rg IS NULL)
                AND (Parameter = 'Ikep' OR Rbe IS NULL)
                AND (Parameter IN ('Ton','Toff') OR Ib IS NULL)
            )
        );

        CREATE TABLE IF NOT EXISTS maximum_ratings (
            TransistorId INTEGER PRIMARY KEY REFERENCES transistors(Id) ON DELETE CASCADE,
            UkeMax      REAL NULL,      -- постоянное напряжение коллектор-эмиттер, В
            UkbMax      REAL NULL,      -- постоянное напряжение коллектор-база (к-б/б-к), В
            UbeMax      REAL NULL,      -- постоянное напряжение база-эмиттер (б-э/э-б), В
            UkeoMax     REAL NULL,      -- постоянное напряжение к-э при разомкнутой базе, В
            IkMax       REAL NULL,      -- постоянный ток коллектора, мА
            IbMax       REAL NULL,      -- постоянный ток базы, мА
            PkMax       REAL NULL,      -- постоянная рассеиваемая мощность коллектора, мВт
            IkPulseMax  REAL NULL,      -- импульсный ток коллектора, мА
            PkPulseMax  REAL NULL,      -- импульсная рассеиваемая мощность, мВт
            PulseDuration REAL NULL,    -- длительность импульса, мкс (обязательна при импульсных значениях)
            TempMin     REAL NULL,     -- минимальная температура среды, °C
            TempMax     REAL NULL,     -- максимальная температура среды, °C
            TempJunctionMax REAL NULL, -- максимальная температура перехода, °C
            Rth         REAL NULL,      -- тепловое сопротивление переход-корпус, °C/Вт
            CONSTRAINT chk_ratings CHECK (
                (UkeMax IS NULL OR UkeMax > 0)
                AND (UkbMax IS NULL OR UkbMax > 0)
                AND (UbeMax IS NULL OR UbeMax > 0)
                AND (UkeoMax IS NULL OR UkeoMax > 0)
                AND (IkMax IS NULL OR IkMax > 0)
                AND (IbMax IS NULL OR IbMax > 0)
                AND (PkMax IS NULL OR PkMax > 0)
                AND (IkPulseMax IS NULL OR IkPulseMax > 0)
                AND (PkPulseMax IS NULL OR PkPulseMax > 0)
                AND (PulseDuration IS NULL OR PulseDuration > 0)
                AND (TempJunctionMax IS NULL OR TempJunctionMax > 0)
                AND (Rth IS NULL OR Rth > 0)
                AND (TempMin IS NULL OR TempMax IS NULL OR TempMin < TempMax)
                AND ((IkPulseMax IS NOT NULL OR PkPulseMax IS NOT NULL) = (PulseDuration IS NOT NULL))
            )
        );
        """;
}
